### ISSUE TITLE
Django loads outdated html file 

### ISSUE THREAD

**Issue by avancayetano** [ProfitMaximizationTool/Profit-Maximization-Tool#3]
sometimes...

**Comment by ProfitMaximizationTool** [comment]
In the demonstration, I (Hans Gabriel H. De Castro) was originally going to show everything from scratch but I panicked so in an attempt to rush, I restored a folder with virtual environment and I did not notice that in the said folder, there is an older version of our repo. That's why when I ran _python manage.py runserver_, it showed the older version of the app.
